import Foundation

/// Canonical list of U.S. colleges for the profile school picker. A fixed list
/// (vs free text) keeps campus leaderboards consistent — classmates resolve to
/// the exact same string. Not exhaustive; expand as users ask. Searched
/// case/diacritic-insensitively, so common abbreviations also need to match —
/// kept in the displayed name where it helps (e.g. "UCLA", "NYU").
enum Colleges {
    static let all: [String] = [
        "Arizona State University",
        "Auburn University",
        "Baylor University",
        "Boston College",
        "Boston University",
        "Bowdoin College",
        "Brandeis University",
        "Brigham Young University (BYU)",
        "Brown University",
        "California Institute of Technology (Caltech)",
        "California Polytechnic State University (Cal Poly)",
        "Carnegie Mellon University",
        "Case Western Reserve University",
        "Clemson University",
        "Colby College",
        "Colgate University",
        "College of William & Mary",
        "Colorado State University",
        "Columbia University",
        "Cornell University",
        "Dartmouth College",
        "Davidson College",
        "DePaul University",
        "Drexel University",
        "Duke University",
        "Elon University",
        "Emory University",
        "Florida International University (FIU)",
        "Florida State University (FSU)",
        "Fordham University",
        "George Mason University",
        "George Washington University (GW)",
        "Georgetown University",
        "Georgia Institute of Technology (Georgia Tech)",
        "Georgia State University",
        "Gonzaga University",
        "Harvard University",
        "Howard University",
        "Indiana University Bloomington",
        "Iowa State University",
        "Johns Hopkins University",
        "Kansas State University",
        "Lehigh University",
        "Louisiana State University (LSU)",
        "Loyola Marymount University (LMU)",
        "Marquette University",
        "Massachusetts Institute of Technology (MIT)",
        "Miami University (Ohio)",
        "Michigan State University",
        "Middlebury College",
        "Mississippi State University",
        "New York University (NYU)",
        "North Carolina State University (NC State)",
        "Northeastern University",
        "Northwestern University",
        "Ohio State University",
        "Oklahoma State University",
        "Oregon State University",
        "Pennsylvania State University (Penn State)",
        "Pepperdine University",
        "Princeton University",
        "Purdue University",
        "Rensselaer Polytechnic Institute (RPI)",
        "Rice University",
        "Rutgers University",
        "Saint Louis University (SLU)",
        "San Diego State University (SDSU)",
        "San Jose State University (SJSU)",
        "Santa Clara University",
        "Stanford University",
        "Stony Brook University",
        "Syracuse University",
        "Temple University",
        "Texas A&M University",
        "Texas Christian University (TCU)",
        "Texas Tech University",
        "The New School",
        "Tufts University",
        "Tulane University",
        "University at Buffalo (SUNY)",
        "University of Alabama",
        "University of Arizona",
        "University of Arkansas",
        "University of California, Berkeley (UC Berkeley)",
        "University of California, Davis (UC Davis)",
        "University of California, Irvine (UC Irvine)",
        "University of California, Los Angeles (UCLA)",
        "University of California, Riverside (UC Riverside)",
        "University of California, San Diego (UCSD)",
        "University of California, Santa Barbara (UCSB)",
        "University of California, Santa Cruz (UCSC)",
        "University of Central Florida (UCF)",
        "University of Chicago",
        "University of Cincinnati",
        "University of Colorado Boulder",
        "University of Connecticut (UConn)",
        "University of Delaware",
        "University of Denver",
        "University of Florida",
        "University of Georgia (UGA)",
        "University of Houston",
        "University of Illinois Chicago (UIC)",
        "University of Illinois Urbana-Champaign",
        "University of Iowa",
        "University of Kansas (KU)",
        "University of Kentucky",
        "University of Maryland, College Park",
        "University of Massachusetts Amherst (UMass)",
        "University of Miami",
        "University of Michigan",
        "University of Minnesota",
        "University of Mississippi (Ole Miss)",
        "University of Missouri (Mizzou)",
        "University of Nebraska-Lincoln",
        "University of Nevada, Las Vegas (UNLV)",
        "University of New Hampshire",
        "University of North Carolina at Chapel Hill (UNC)",
        "University of Notre Dame",
        "University of Oklahoma",
        "University of Oregon",
        "University of Pennsylvania (Penn)",
        "University of Pittsburgh",
        "University of Rochester",
        "University of South Carolina",
        "University of South Florida (USF)",
        "University of Southern California (USC)",
        "University of Tennessee",
        "University of Texas at Austin (UT Austin)",
        "University of Texas at Dallas (UTD)",
        "University of Utah",
        "University of Vermont (UVM)",
        "University of Virginia (UVA)",
        "University of Washington",
        "University of Wisconsin-Madison",
        "Vanderbilt University",
        "Villanova University",
        "Virginia Commonwealth University (VCU)",
        "Virginia Tech",
        "Wake Forest University",
        "Washington State University",
        "Washington University in St. Louis (WashU)",
        "Wellesley College",
        "Wesleyan University",
        "West Virginia University",
        "Williams College",
        "Yale University",
    ]

    /// Case- and diacritic-insensitive substring search, ranked so prefix
    /// matches surface first. Empty query returns the full list.
    static func search(_ query: String, limit: Int = 60) -> [String] {
        let q = query.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
            .trimmingCharacters(in: .whitespaces)
        guard !q.isEmpty else { return Array(all.prefix(limit)) }
        let scored = all.compactMap { name -> (String, Int)? in
            let folded = name.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
            guard let range = folded.range(of: q) else { return nil }
            // Lower score = better: prefix beats mid-word, earlier beats later.
            return (name, folded.distance(from: folded.startIndex, to: range.lowerBound))
        }
        return scored.sorted { $0.1 != $1.1 ? $0.1 < $1.1 : $0.0 < $1.0 }
            .prefix(limit).map(\.0)
    }
}
